sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "kkp403@gmail.com"
  - git config --global user.name "Jinho"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "puCh/2EuMHB90Fq8q+ftEvlNDn4yZ7Lw1fCbUiCDDO+jfYkqG9beCBixKAZn9OOBiLT4M98m0p/KWwgUaiW3sSsBfs+2JJUrp+w9NJyBsr98c04hnMc5h3p91Pc0W5hUelnpIggWf6a2W5WYLhqNCDEnaOfwypg4b8x/ycRQvpG2RiQD7ZTJZLBLu0Se7fdxO1+HAbKt4/6o83Fxx1892zSv5wbzJdHWr2AG5BmgWZ58e2BsTUuvnaOJCjLHDScrsN/aTWuIuSpZgP7voJD1bI4sYqr0CKw+oc5kbQ3y4O
   AxBdFRLsrgTpUGaCpbuEYnF4Osuru0UCBxkNLgh3tcHBHVbmm+jPRx/5AA8OifgerEInkJ8GxGwvEVOQJ30+00y3z0kMsvVAC/VEMSWN0M0jSZYBvm3FbfEnKQmIjmEH4lA1aw47LtCil+dA6/cA0ISD2HcJ6flWoVAOPMAMR1ly/48udFwvR1MPAT+SYixweKV0pvSUghvpf2KTaARzNe77ZR14gzkvabSe1FQ8wXaf64Yn1Z+w5D0aRT+I1ifevprylyNhKgGQNfvHkIU5MEABPMSzwYdsPY3gmc23YPwtdjZOE438V
   9d4rH817H/9HTfu2ZWE+Okpa+lh1/3AKPyLsV2Autz5tpuZrFN2RuReI46M9cNZEMaVQXMxJYn4Q="


branches:
  only:
    - master