sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "moon9342@gmail.com"
  - git config --global user.name "SungHoon Moon"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "KT662bEPeQucbqwnscWLxcmUvKnXxQE6OtYYLabOe1UiyGTlmQf+/ww7iwNTaLs7NG/M5j3Iovu7vamvJX9X23DkRNY94SWxtTl7jwiVv/krxPGPQfNkog9YNfhGHTfDqGJivFjg3NydNs2KW2BquDXDIFXt57/OtZP7mtlGfj5hthYRuvV+
            0na4a7XxNPmXm+BFdO6LBPbk9XOxNq8K7EmceC9MboOWEbC46FF5HG0XUrgWpENTysyXTMvq+TwN8swwSZsoYBScvXgzVLpRCPtVvEM9ADfYAKddl4bPk2VukYzJB9xtzJDHGCGN5To0vQJuqn85h9uFQKFvY1XgRJgjSJAAEPc5OBKfYcIdg9pc0DVcmrk
            K739zS887+s81agw6IXYqCcZvZUs+DamdgVZ/NWGP8Hp736UtC+sa6QJYpMe2z4xdO93LvlxXJUDHrisw0LETftV2tQDRb+/b9nPTekvDk+vUWWKpW5VoOnd7+XseM8Eq/buWbRO6AL9wSwHDDsIVfSKmf/BNZJgBkp7lkoRp7GHF4g+q0XllRqVsQJdmiZ
            CmAauhdevqbO/RBmHOq5PkL+krmKkxeWKB4UOXE+eQ1EQbrRaiXbdMyJ5VszvCZAlRMKXcN7ASrb086ecBhJ9agXf1hhnGxa3RW8eXfKI5WR1gzQzfX/Ez/9A="
branches:
  only:
    - master