sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "kkp403@gmail.com"
  - git config --global user.name "Jinho Kim"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "Lq5yTMos+k4YRlrBr5ftHfb35OInXzee8otDEybWl1q5nu0lI4OYpDRrdeYSmkstg3WLjlQEyA13h3LVVxj/vk2vBnB9kWVTGP0Dq48iXmeKJgF9XfyWVFvcfUEfDU2+r2bhINwaTa47dwjGtWsK6DpeR2tnDqla6o+qdwpJaM6NvQBFFaDkAseut23hsyjYOTsBckfThU2H0jzId5LRo9AOgEhmK0ZH1EMzyUUinlu7aN9wwAsjTFY 3urDpqcygmzru1m4FtEY+us44ukmiYMuPVNybqdAIwGNQ+JrvwRQrNRRfTZ5sgeMZWj1y+0c7haQoSc+YujlRpuLiYHOzEXNcoFzU0hEXCIZJLSXm4pjzJ7W/E7sVJaCwjFeJG31Oihjn+DhuDg3QyBQcg6flTi+aRoG2HbFTXVheMzCBPPGZGeZi5gpdva2/P1kZOKBmyGnZ4kELlhznKLgOHPJdp2zylrTKM1vnN0Khvwf8pEOPNijZflKWG7bBGJ/cxNaHrYeZSAy3qpx7Xzil9Froze46x+0l4aVNUk14dl8Y9LtQBx2ftHqtiRDrCWqut+PIw8LryqBNdQNEwMm6Ofzxk5FV8R+ruSLCV+cHvoikdKcGHQCn+gNvyKYRxJJfTsKAEYtOxS20z0rb+lIYHUqFG+Pufxnpw72b2bqlwChNjvs="
branches:
  only:
    - master